version: '3'

services: 


  db: 
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql-entrypoint:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - nodenet


  nodeapp:
    build:
      context: app
    container_name: nodeapp
    networks: 
      - nodenet
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db

  nginx-reverse:
    build:
      context: nginx
    container_name: nginx-reverse
    networks: 
      - nodenet
    ports:
      - "8080:80"
    depends_on:
      - nodeapp


networks: 
  nodenet:
    driver: bridge      